### ISSUE TITLE
About the license

### ISSUE THREAD

**Issue by ghost** [kazuhikoarase/kazuhikoarase.github.io#1]
Excuse me, could you tell me what the license of your awesome "SimcirJS(a.k.a. Simcir)"  is ?
I want to make a small and simple game for teaching little kids some basic electrical circuit knowledge. But I think some  operations are not very easy for litthle kids to understand. So I want  to make a litthle small changes.
So, could I modify your codes, and share with others **as open source**?  Of course, I will  stress the contribution you made. For example, I will write down your github pages url or your twitter account.

**Comment by kazuhikoarase** [comment]
Hi,
It's under the MIT license.

https://github.com/kazuhikoarase/simcirjs

**Comment by ghost** [comment]
Thank you very much !! 👍
